version: '3.7'

services:
  philagov:
    image: ${PHILAGOV_IMAGE}
    depends_on:
      - db
    build: .
    command: dev
    ports:
      - ${INSTALATION_PORT}:443
    volumes:
      # Phila.gov git project
      - ./phila.gov:/phila.gov
      - ssl-cert-persistence:/etc/ssl

      # This is used when downloading the database
      - ./db:/db
      # - ./scripts/mysql-config.sh:/scripts/mysql-config.sh

      # Useful while developing the docker environment
      - ./scripts:/scripts
      - ./nginx:/etc/nginx
      - ./phila-standards:/phila.gov/wp/wp-content/themes/phila.gov-theme/node_modules/phila-standards
      - ./supervisor.conf:/etc/supervisor/conf.d/supervisor.conf
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: philagov
      PHILA_PLUGINS_BUCKET: phila-wp-plugins
      PHILA_MEDIA_BUCKET: phila-media-sync
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:?AWS_ACCESS_KEY_ID should not be empty}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:?AWS_SECRET_ACCESS_KEY should not be empty}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN:?AWS_SESSION_TOKEN should not be empty}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-us-east-1}
      AQI_KEY: $AQI_KEY
      SWIFTYPE_ENGINE: $SWIFTYPE_ENGINE
      GOOGLE_CALENDAR: $GOOGLE_CALENDAR
      JWT_AUTH_SECRET_KEY: $JWT_AUTH_SECRET_KEY

      DOMAIN: localhost:${INSTALATION_PORT}

      #DB CONFIG
      PHILA_DB_BUCKET: $PHILA_DB_PATH
      PHILA_DB_FILE: $PHILA_DB_FILE
  db:
    platform: linux/x86_64 #required to work on M1 mac
    image: mysql:5.7
    container_name: db-${INSTALATION_NAME}
    ports:
     - 3307-3407:3306
    volumes:
      - db-persistence:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wp
      MYSQL_ROOT_PASSWORD: philagov

volumes:
  db-persistence:
    name: db-${INSTALATION_NAME}
  ssl-cert-persistence:
    name: ssl-${INSTALATION_NAME}
